### ISSUE TITLE
Cannot change literal expression name

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js-properties-panel#103]
### Describe the Bug

When changing the name of the literal expression then the editor blows up:

![capture ZzRmCW_optimized](https://github.com/user-attachments/assets/b8865118-90ac-41af-b5ee-05f07734ef77)

Related to [this change](https://github.com/bpmn-io/dmn-js/pull/893/files#r1833112494) in dmn-js.

### Steps to Reproduce

1. Update name for literal expression from properties panel
2. See that editor blows up

### Expected Behavior

Name can successfully updated.

### Environment

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: `main`

**Comment by barmac** [comment]
Ouch. This is a critical bug since the error breaks the Modeler. It's present in Camunda Modeler 5.29.0
