### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js-properties-panel#3]
Migrate to min-dash + implement functions missing in min-dash

Closes #2.

**Comment by philippfromme** [comment]
Fails on CI since min-dash uses JS features that are not supported in PhantomJS.

**Comment by nikku** [comment]
What exactly _fails_? We should either work around the min-dash issue in the properties panel or test the panel against Firefox / Chrome on CI instead.

**Comment by barmac** [comment]
We don't use lodash on master anymore.
