### ISSUE TITLE
Release v1.0.0-alpha.0 

### ISSUE THREAD

**Issue by smbea** [bpmn-io/dmn-js-properties-panel#30]
* [x] https://github.com/bpmn-io/dmn-js-properties-panel/issues/33
* [x] update changelog

Related to camunda/camunda-dmn-js/issues/1

Requires https://github.com/bpmn-io/dmn-js-properties-panel/issues/33

**Comment by barmac** [comment]
Done, cf. https://www.npmjs.com/package/dmn-js-properties-panel/v/1.0.0-alpha.1
