### ISSUE TITLE
SaveXML causes crash when in decision table view

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js-properties-panel#37]
__Describe the Bug__

When I save XML from the decision table view, the properties panel crashes with:

```
TypeError
Cannot read properties of undefined (reading 'split')
getRawType
[https://78dwru.csb.app/node_modules/dmn-js-properties-panel/dist/index.esm.js:324:15]()
getConcreteType
[https://78dwru.csb.app/node_modules/dmn-js-properties-panel/dist/index.esm.js:307:10]()
getTypeLabel
[https://78dwru.csb.app/node_modules/dmn-js-properties-panel/dist/index.esm.js:319:26]()
```

It seems that the properties panel is still active even though in the decision table view it shouldn't do any work. The error originates in [the PanelHeaderProvider](https://github.com/bpmn-io/dmn-js-properties-panel/blob/master/src/render/PanelHeaderProvider.js#L15).

__Steps to Reproduce__

1. Open [this codesandbox](https://codesandbox.io/s/relaxed-williams-78dwru?file=/src/index.js)
2. Go to decision table view
3. Click "Save"

__Expected Behavior__

No crashes.

__Environment__

- Host (Browser/Node version), if applicable: any
- OS: MacOS
- Library version: 1.0.0-alpha.1

**Comment by barmac** [comment]
This bug is critical so we need to fix this before the upcoming release of Camunda Modeler.

**Comment by barmac** [comment]
The direct reason of the error is that we try to get type of implicit root:

![image](https://user-images.githubusercontent.com/28307541/159027845-1f035ee1-0800-4ce2-a927-919ee75cedaf.png)

I wasn't able to reproduce it in a test case but can do it manually.

**Comment by pinussilvestrus** [comment]
It does update the root, which it shouldn't

![image](https://user-images.githubusercontent.com/9433996/159232448-f37245f9-3492-4602-ac00-4ee11adb46dc.png)

What we could do is to [prevent the update ](https://github.com/bpmn-io/dmn-js-properties-panel/blob/master/src/render/DmnPropertiesPanel.js#L116), like we do on selection changes

```js
if (isImplicitRoot(rootElement)) {
  return;
}
```

**Comment by pinussilvestrus** [comment]
On `saveXML` the align-to-origin extension tries to get the root element via canvas. To fix this, we have to make sure the properties panel doesn't update on implicit roots.
