### ISSUE TITLE
Support jQuery as Parent Node of Properties Panel Renderer

### ISSUE THREAD

**Issue by PaulLunkenheimer-viadee** [bpmn-io/dmn-js-properties-panel#50]
Similar to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/729

I am happy to implement a fix.

__What should we do?__

Pre 1.0 one could attach the properties panel to a parent node which was provided as jQuery. Now, this seems to have been deprecated:
https://github.com/bpmn-io/dmn-js-properties-panel/blob/master/src/render/DmnPropertiesPanelRenderer.js#L76

__Why should we do it?__

Supporting jQuery as parent node to the properties panel would be

- practical
- in line with previous releases
- especially it would go along with the way it is done in dmn-js itself.

**Comment by nikku** [comment]
We'd be glad to receive a contribution here.
