### ISSUE TITLE
Error message for `id` vanishes

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js-properties-panel#85]
### Describe the Bug

The error message shown when an invalid `id` is specified is not shown anymore in `dmn-js-properties-panel@3.3.0`:

![capture BtEDLH_optimized](https://github.com/bpmn-io/dmn-js-properties-panel/assets/58601/d2b5c31b-0a39-4a99-882d-60a14dd75d35)

This seems to be related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1021.

### Steps to Reproduce

1. `npm start`
2. select DRD, enter `AAA` as an ID
3. select Decision, enter `AAA` an ID
4. __see error shown for a split second and then disappear__

### Expected Behavior

Error message `ID must not be empty.` or duplicate ID message are shown consistently.

### Environment

- Host (Browser/Node version), if applicable: Chrome 110
- OS: Linux
- Library version: dmn-js-properties-panel@3.3.0

---

Raised internally via [this thread](https://camunda.slack.com/archives/C0693F1NFK5/p1712084524468569)

**Comment by nikku** [comment]
Requires fix along the lines of https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1022.

**Comment by barmac** [comment]
Released as v3.3.1
