### ISSUE TITLE
Sanitize entities when building HTML

### ISSUE THREAD

**Issue by barmac** [bpmn-io/dmn-js-properties-panel#9]
#### Description

We do not properly sanitize entities (labels, ...) we build the properties panel UI from. This leads to UI bugs or script injection in the worst case.

#### Expected Behavior 

We properly sanitize user input in all places where it is being used to build the properties panel.

#### Additional Context

Original issue: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/296

**Comment by nikku** [comment]
Released as `v0.3.0`.
